### ISSUE TITLE
Why `pre` tag is not a available in markdown_tags?

### ISSUE THREAD

**Issue by hariharasudhan-nineleaps** [yourcelf/bleach-whitelist#11]
Does  `pre` is not safe tag?. if not why it is not allowed in `markdown_tags`.

**Comment by i1caro** [comment]
Bump

**Comment by yourcelf** [comment]
`pre` is now included in markdown safe tags, in the renamed https://github.com/yourcelf/bleach-allowlist project.  This project under this name will not get further updates.
