### ISSUE TITLE
update terminology to match bleach-whitelist -> allowed-list, bleach_whitelist -> bleach_allowed_list

### ISSUE THREAD

**Issue by graingert** [yourcelf/bleach-whitelist#12]
@yourcelf bleach switched from whitelist to allowed list here: https://github.com/mozilla/bleach/pull/265

I think this project should follow suit

**Comment by yourcelf** [comment]
I agree.  It'll be a biggish change since it's changing the project name in addition to the package name.  I won't be able to get to it for the next week; but am setting myself a reminder to come back to this as soon as I can.

**Comment by graingert** [comment]
> I agree.

Great stuff! I've created and added you as owner for these project on pypi:

https://pypi.org/project/bleach-allowed-list/
https://pypi.org/project/bleach-allowlist/

feel free to remove me from the collaborators

**Comment by graingert** [comment]
see PR #13

**Comment by yourcelf** [comment]
This is fixed.  @graingert thanks very much for the PR and for reserving the pypi projects.

I've cherry-picked parts of the PR it, but gone with `bleach-allowlist` as a less-cumbersome-to-me alternative rather than bleach-allowed-list`.  https://github.com/yourcelf/bleach-allowlist/

**Comment by graingert** [comment]
You disabled universal wheels?
