### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by marcinkuzminski** [yourcelf/bleach-whitelist#6]
Hi,

Thanks for making this lib !

Would it be possible to release this under an MIT license? 
Having no license is a problem in some cases for using this library. MIT is a safe option imho.

**Comment by yourcelf** [comment]
While there was no LICENSE file, `setup.py` referenced the license as 'BSD license', so I'm adding 2-clause BSD. Should be more or less compatible with whatever needs you'd have under an MIT license.

**Comment by marcinkuzminski** [comment]
Ahh haven't noticed the setup.py reference. But a dedicated LICENSE file would be helpfull.

Thanks
