### ISSUE TITLE
Sub and sup in markdown

### ISSUE THREAD

**Issue by darbula** [yourcelf/bleach-whitelist#9]
Is there are reason why sub and sup tags are not whitelisted for markdown?

**Comment by yourcelf** [comment]
No particular reason, it's just an omission. I'll accept a PR to add them!

**Comment by darbula** [comment]
Great, thank you. Here it is https://github.com/yourcelf/bleach-whitelist/pull/10

**Comment by yourcelf** [comment]
Thanks, merged, and deployed to pypi as 0.0.10.
